### ISSUE TITLE
Script not showing in menu on SX20IS

### ISSUE THREAD

**Issue by clampak** [AndrewHazelden/CHDK-Countdown-Intervalometer#1]
I've loaded the counter.bas script into the SCRIPTS folder on the SD card, but it does not appear in the CHDK menu in the camera.  The other scripts are there, but not counter.bas.  Do you have any idea of why this might happen?

**Comment by clampak** [comment]
Nevermind, it was the way I had the SD card formatted.  I had two partitions, and the script should have been on the second partition (the one images get recorded to) but it wasn't.  All fine now.

**Comment by AndrewHazelden** [comment]
Hi. I'm happy to hear you were able to get the script to work in the end.

Cheers,
Andrew
